//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novi_POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProizvod
    {
        public tblProizvod()
        {
            this.tblTransakcijaStavka = new HashSet<tblTransakcijaStavka>();
        }
    
        public int proizvodId { get; set; }
        public string naziv { get; set; }
        public Nullable<decimal> cena { get; set; }
        public byte[] slika { get; set; }
        public Nullable<int> kategorijaId { get; set; }
    
        public virtual tblKategorija tblKategorija { get; set; }
        public virtual ICollection<tblTransakcijaStavka> tblTransakcijaStavka { get; set; }
    }
}
