//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novi_POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransakcija
    {
        public tblTransakcija()
        {
            this.tblTransakcijaStavka = new HashSet<tblTransakcijaStavka>();
        }
    
        public int transakcijaId { get; set; }
        public Nullable<System.DateTime> datumTransakcije { get; set; }
    
        public virtual ICollection<tblTransakcijaStavka> tblTransakcijaStavka { get; set; }
    }
}
