//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novi_POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransakcijaStavka
    {
        public int transakcijaStavkaId { get; set; }
        public Nullable<int> transakcijaId { get; set; }
        public Nullable<int> proizvodId { get; set; }
        public Nullable<int> korisnikId { get; set; }
    
        public virtual tblKorisnici tblKorisnici { get; set; }
        public virtual tblProizvod tblProizvod { get; set; }
        public virtual tblTransakcija tblTransakcija { get; set; }
    }
}
